# Generated by Django 4.2 on 2023-04-18 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Video",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("video_name", models.CharField(max_length=100)),
                ("poster_url", models.CharField(max_length=200)),
                ("video_url", models.CharField(max_length=200)),
                ("pub_data", models.DateTimeField(verbose_name="date published")),
            ],
        ),
    ]
