# Generated by Django 4.2 on 2023-04-23 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("polls", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="IYF_Movie",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("movie_name", models.CharField(max_length=100)),
                ("movie_type", models.CharField(max_length=100)),
                ("movie_addr", models.CharField(max_length=200)),
                ("movie_time", models.CharField(max_length=50)),
                ("movie_mark", models.CharField(max_length=10)),
                ("movie_actor", models.CharField(max_length=100)),
                ("movie_poster", models.CharField(max_length=300)),
            ],
        ),
    ]
